# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jiahao.luan@epfl.ch
author_name: Jiahao Luan
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
mimetype: ''
mimetype_name: ''
project_short_description: Show a random NASA Astronomy Picture of the Day in JupyterLab
    panel
python_name: jupyterlab_apod
repository: https://github.com/down-street/jupyterlab_extension_demo
test: true
viewer_name: ''

